### ISSUE TITLE
Rewrite pythonscript to C++ to make it faster.

### ISSUE THREAD

**Issue by NaifHagatulah** [AdamTovatt/camera-server#27]
Rewrite the camera image taking script so it works faster and more efficient. Goal is to write this in C++ because opencv is a c++ lib.

**Comment by AdamTovatt** [comment]
Will close this as the problem this was meant to fix is probably not related to the implementation currently being in Python. There is something wrong with the hardware of the raspberry pi zero it is running on and while a C++ implementation would be nice it is not a priority since it (probably) works about as well in Python. The problem seems to have been resolved or at least improved by changing the clock frequency and voltage overloading of the cpu on the raspberry pi in question. See this thread: https://github.com/raspberrypi/linux/issues/2555
